import pytest
import os
import shutil
import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch
from llama_index.core import Document


@pytest.fixture(scope="session")
def test_data_dir():
    """
    Fixture providing path to test data directory
    """
    return Path(__file__).parent / "test_data"


@pytest.fixture
def temp_docs_dir(tmp_path):
    """
    Fixture creating a temporary docs directory with sample files
    """
    docs_dir = tmp_path / "docs"
    docs_dir.mkdir()
    
    # Create sample markdown files
    (docs_dir / "doc1.md").write_text("""
# Authentication Guide

## Overview
Our system uses OAuth 2.0 for authentication.

## Getting Started
To authenticate, you need to obtain an API key from the dashboard.

## API Key Requirements
- Must be at least 32 characters
- Include both letters and numbers
- Keep it secret and secure
    """)
    
    (docs_dir / "doc2.md").write_text("""
# Password Reset

## How to Reset Password
1. Go to login page
2. Click "Forgot Password"
3. Enter your email
4. Check your inbox for reset link

## Password Requirements
- Minimum 8 characters
- At least one uppercase letter
- At least one number
- At least one special character
    """)
    
    (docs_dir / "doc3.txt").write_text("""
API Rate Limits

Our API has the following rate limits:
- Free tier: 100 requests per hour
- Pro tier: 1000 requests per hour
- Enterprise: Unlimited requests

Rate limit headers are included in every response.
    """)
    
    return str(docs_dir)


@pytest.fixture
def temp_storage_dir(tmp_path):
    """
    Fixture creating a temporary storage directory for index
    """
    storage_dir = tmp_path / "storage"
    storage_dir.mkdir()
    return str(storage_dir)


@pytest.fixture
def sample_documents():
    """
    Fixture providing sample Document objects
    """
    return [
        Document(
            text="Authentication uses OAuth 2.0. You need an API key to access the system.",
            metadata={"file_name": "auth.md", "file_path": "/docs/auth.md"}
        ),
        Document(
            text="To reset your password, go to the login page and click forgot password.",
            metadata={"file_name": "password.md", "file_path": "/docs/password.md"}
        ),
        Document(
            text="API rate limits are 100 requests per hour for free tier.",
            metadata={"file_name": "limits.md", "file_path": "/docs/limits.md"}
        )
    ]


@pytest.fixture
def sample_nodes():
    """
    Fixture providing sample Node objects (chunks)
    """
    from llama_index.core.schema import TextNode
    
    return [
        TextNode(
            text="Authentication uses OAuth 2.0. You need an API key.",
            metadata={"file_name": "auth.md"}
        ),
        TextNode(
            text="To reset your password, click forgot password on login page.",
            metadata={"file_name": "password.md"}
        ),
        TextNode(
            text="Free tier has 100 requests per hour rate limit.",
            metadata={"file_name": "limits.md"}
        )
    ]


@pytest.fixture
def mock_config(temp_docs_dir, temp_storage_dir, monkeypatch):
    """
    Fixture providing mocked configuration
    """
    monkeypatch.setattr("config.Config.DOCS_DIR", temp_docs_dir)
    monkeypatch.setattr("config.Config.STORAGE_DIR", temp_storage_dir)
    monkeypatch.setattr("config.Config.CHUNK_SIZE", 256)
    monkeypatch.setattr("config.Config.CHUNK_OVERLAP", 20)
    monkeypatch.setattr("config.Config.TOP_K", 2)
    monkeypatch.setattr("config.Config.OPENAI_API_KEY", "test-key-123")
    
    from config import Config
    return Config


@pytest.fixture
def mock_embedding_model():
    """
    Fixture providing a mocked embedding model
    """
    mock_model = MagicMock()
    mock_model.get_text_embedding.return_value = [0.1] * 384
    return mock_model


@pytest.fixture
def mock_llm():
    """
    Fixture providing a mocked LLM
    """
    mock_llm = MagicMock()
    mock_llm.complete.return_value.text = "This is a test answer generated by the LLM."
    return mock_llm


@pytest.fixture(autouse=True)
def reset_settings():
    """
    Fixture to reset LlamaIndex Settings between tests
    """
    from llama_index.core import Settings
    Settings.embed_model = None
    Settings.llm = None
    yield
    Settings.embed_model = None
    Settings.llm = None


@pytest.fixture
def cleanup_storage(temp_storage_dir):
    """
    Fixture to clean up storage directory after tests
    """
    yield
    if os.path.exists(temp_storage_dir):
        shutil.rmtree(temp_storage_dir)